#pragma once

#include <cstdint>

namespace petdaq {

/**
 * A single simulated detector hit.
 *
 * In a real DAQ system, this structure would normally be populated from
 * hardware/DMA buffers rather than generated by software. The fields model
 * the information needed by later calibration and reconstruction stages.
 *
 * Keeping the event compact is intentional: acquisition systems can process
 * millions of events per second, so every byte affects memory bandwidth and
 * cache residency.
 */
struct DetectorEvent final {
    std::uint64_t timestamp_ns{};
    std::uint16_t detector_id{};
    std::uint16_t channel{};
    std::uint32_t raw_energy{};
};

static_assert(sizeof(DetectorEvent) == 16,
              "DetectorEvent is expected to remain a compact 16-byte record.");

} // namespace petdaq
